name: Deno

on:
  push:
    branches: ["Barabasbalazs-setup-test-workflow", "main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        env:
          MEILI_MASTER_KEY: 'masterKey'
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'

    name: Deno tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0
        with:
          deno-version: v2.x

      # - name: Run linter
      #   run: deno lint

      - name: Run tests
        run: deno test --allow-env --allow-net
